name: Generate and Deploy Doxygen Docs

# Запуск workflow при пуше в ветку task_03
on:
  push:
    branches:
      - task_03

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем Doxygen
      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      # 3. Генерируем документацию
      - name: Generate Doxygen documentation
        working-directory: trunk/ii02825/task_03  # здесь лежит Doxyfile
        run: doxygen Doxyfile

      # 4. Публикуем документацию на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: trunk/ii02825/task_03/doc/html
